# Workflow to generate a visually appealing Pac-Man Contribution Graph
name: Generate Pac-Man Animation

# Trigger the workflow on a schedule, manual dispatch, or push to main
on:
  schedule:
    - cron: "0 */12 * * *" # Run every 12 hours at the start of the hour
  workflow_dispatch: # Allow manual triggering via GitHub UI
  push:
    branches:
      - main

# Define the job to generate and publish the Pac-Man graph
jobs:
  generate:
    # Set permissions to allow writing to the repository
    permissions:
      contents: write
    # Use the latest Ubuntu runner for compatibility
    runs-on: ubuntu-latest
    # Set a timeout to prevent hanging
    timeout-minutes: 5

    steps:
      # Step 1: Generate Pac-Man contribution graph SVGs
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }} # Automatically set to 'brlamit'

      # Step 2: Push generated SVGs to the 'output' branch
      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GitHub token for authentication